import { expect, Page, test } from '@playwright/test';

async function login(page:Page,email:string){await page.goto('/login');await page.getByLabel('E-mail').fill(email);await page.getByLabel('Senha').fill('demo123');await page.getByRole('button',{name:'Acessar',exact:true}).click();await expect(page).toHaveURL(/\/app\//);}

const baseQuestion=(id:string,title:string,sortOrder:number)=>({id,dimensionKey:id,dimensionTitle:title,prompt:`Enunciado ${title}`,inputType:'scale',visibility:'restricted',sortOrder,isRequired:true,collectEvidenceOnExtreme:false,isSensitive:false,options:[]});

test('RH cria, reordena e remove pergunta da biblioteca',async({page})=>{
  await login(page,'rh@demo.local');
  let questions=[baseQuestion('q1','Primeira',1),baseQuestion('q2','Segunda',2)];
  const payload=()=>({scale:[],defaultLibrary:{id:'default',name:'Padrao',description:'',questionCount:2},manualLibrary:{id:'manual',name:'Manual',description:'',questionCount:questions.length},cycleLibraries:[],questionGroups:[{id:'manager',key:'manager',title:'Gestor',description:'',questions}]});
  await page.route('**/api/evaluations/library**',async route=>{const req=route.request();const url=new URL(req.url());if(req.method()==='GET')return route.fulfill({status:200,json:payload()});if(url.pathname.endsWith('/reorder')){const body=req.postDataJSON() as {questionIds:string[]};questions=body.questionIds.map((id,index)=>({...questions.find(q=>q.id===id)!,sortOrder:index+1}));return route.fulfill({status:200,json:payload()});}if(req.method()==='POST'){const body=req.postDataJSON() as Record<string,unknown>;questions.push({...baseQuestion('q-new',String(body.dimensionTitle),Number(body.sortOrder)),prompt:String(body.prompt)});return route.fulfill({status:201,json:payload()});}if(req.method()==='DELETE'){questions=questions.filter(q=>!url.pathname.endsWith(q.id));return route.fulfill({status:200,json:payload()});}return route.continue();});
  await page.goto('/app/evaluations');await page.getByRole('button',{name:'Biblioteca'}).click();await page.getByRole('button',{name:'Nova pergunta'}).click();await page.getByLabel('Chave da dimensao').fill('nova');await page.getByLabel('Titulo da dimensao').fill('Nova pergunta E2E');await page.getByLabel('Enunciado').fill('Enunciado novo E2E');await page.getByRole('button',{name:'Salvar pergunta'}).click();await expect(page.getByText('Nova pergunta E2E',{exact:true})).toBeVisible();
  const added=page.locator('.questions article').filter({hasText:'Nova pergunta E2E'});await added.getByRole('button',{name:'Subir'}).click();await expect(page.locator('.questions article').nth(1)).toContainText('Nova pergunta E2E');page.once('dialog',dialog=>dialog.accept());await page.locator('.questions article').filter({hasText:'Nova pergunta E2E'}).getByRole('button',{name:'Remover'}).click();await expect(page.getByText('Nova pergunta E2E',{exact:true})).toHaveCount(0);
});

test('admin cria, publica e arquiva questionario',async({page})=>{
  await login(page,'admin@demo.local');
  const cycle={id:'cycle-72',title:'Ciclo 7.2',semesterLabel:'2026.2',dueDate:'2026-12-20',targetGroup:'Todos',status:'Liberado',libraryId:'default',libraryName:'Padrao',modelName:'Padrao',isEnabled:true};
  const person={id:'person-72',name:'Pessoa 7.2',roleTitle:'Analista',area:'Produto',workUnit:null,workMode:null,managerPersonId:null,managerName:null,areaManagerPersonId:null,areaManagerName:null,employmentType:'internal'};
  const questions=Array.from({length:7},(_,index)=>({...baseQuestion(`pq${index+1}`,`Pergunta ${index+1}`,index+1),questionnaireId:'published-ready',promptText:`Enunciado ${index+1}`}));
  let questionnaires:any[]=[{id:'published-ready',cycleId:cycle.id,revieweePersonId:person.id,relationshipType:'peer-same-area',sourceLibraryId:null,title:'Questionario pronto',description:'',status:'draft',questionCount:7,visibilityLevel:'restricted',versionNumber:1,publishedAt:null,questions}];
  await page.route('**/api/evaluations/cycles',r=>r.fulfill({status:200,json:[cycle]}));await page.route('**/api/people',r=>r.fulfill({status:200,json:[person]}));await page.route('**/api/evaluations/assignments',r=>r.fulfill({status:200,json:[]}));
  await page.route('**/api/evaluations/questionnaires**',async route=>{const req=route.request();const url=new URL(req.url());if(req.method()==='GET')return route.fulfill({status:200,json:questionnaires});if(req.method()==='POST'&&url.pathname.endsWith('/questionnaires')){const body=req.postDataJSON() as any;const created={...body,id:'created-72',status:'draft',questionCount:0,versionNumber:1,publishedAt:null,questions:[]};questionnaires=[created,...questionnaires];return route.fulfill({status:201,json:created});}const id=url.pathname.split('/').at(-2);const item=questionnaires.find(q=>q.id===id);if(req.method()==='POST'&&url.pathname.endsWith('/publish')){item.status='published';item.publishedAt=new Date().toISOString();return route.fulfill({status:200,json:item});}if(req.method()==='POST'&&url.pathname.endsWith('/archive')){item.status='archived';return route.fulfill({status:200,json:item});}return route.continue();});
  await page.goto('/app/evaluations');await page.getByRole('button',{name:'Questionarios'}).click();await page.getByRole('button',{name:'Novo questionario'}).click();await page.getByLabel('Titulo').fill('Novo questionario 7.2');await page.getByRole('button',{name:'Salvar questionario'}).click();await expect(page.locator('.list button').filter({hasText:'Novo questionario 7.2'})).toBeVisible();
  await page.locator('.list button').filter({hasText:'Questionario pronto'}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Publicar'}).click();await expect(page.locator('.detail')).toContainText('published');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Arquivar'}).click();await expect(page.locator('.detail')).toContainText('archived');
});

test('administrador visualiza biblioteca sem controles de mutacao',async({page})=>{await login(page,'admin@demo.local');await page.goto('/app/evaluations');await page.getByRole('button',{name:'Biblioteca'}).click();await expect(page.getByRole('heading',{name:'Biblioteca de perguntas'})).toBeVisible();await expect(page.getByRole('button',{name:'Nova pergunta'})).toHaveCount(0);});
