import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { firstValueFrom, forkJoin } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { ApiError } from '../../core/http/api-error';
import { Person, PeopleService } from '../people/people.service';
import { AuditService, AuditEntry } from '../audit/audit.service';
import { AuditTrailComponent } from '../audit/audit-trail.component';
import { AdminUser, CreateUserPayload, UpdateUserPayload, UserRoleKey, UserStatus, UsersService } from './users.service';

@Component({ selector: 'app-users-page', imports: [ReactiveFormsModule, AuditTrailComponent], template: `
<section class="users" aria-labelledby="users-title"><header><div><p>Cadastro</p><h1 id="users-title">Usuarios</h1><span>Gerencie acessos, perfis e status.</span></div><button type="button" (click)="startCreate()">Novo usuario</button></header>
@if (error()) { <p class="error" role="alert">{{ error() }}</p> }
<section class="journey" aria-label="Jornada de acesso"><div><span>Estrutura cadastrada</span><strong>{{ people().length }}</strong></div><div><span>Acessos ativos</span><strong>{{ activeUsers() }}</strong></div><div><span>Acessos pendentes</span><strong>{{ pendingAccess() }}</strong></div><div><span>Acessos inativos</span><strong>{{ inactiveUsers() }}</strong></div></section>
<section class="steps" aria-label="Passo a passo de provisionamento"><article [class.done]="availablePeople().length > 0"><strong>1. Pessoa pronta</strong><span>{{ availablePeople().length ? 'Escolha uma pessoa sem acesso para iniciar.' : 'Todas as pessoas ja possuem usuario vinculado.' }}</span></article><article [class.done]="form.controls.email.value && form.controls.password.value.length >= 6"><strong>2. Credenciais</strong><span>Defina email valido e senha inicial com pelo menos 6 caracteres.</span></article><article [class.done]="form.controls.roleKey.value && form.controls.status.value"><strong>3. Perfil de acesso</strong><span>Perfil e status configurados.</span></article><article [class.done]="!validation() && editing()"><strong>4. Criacao</strong><span>Finalize as etapas anteriores para liberar o acesso.</span></article></section>
@if (editing() && !selectedUser()) { <form [formGroup]="form" (ngSubmit)="save()"><label>Pessoa <select formControlName="personId" (change)="applyPersonSuggestion($any($event.target).value)"><option value="" disabled>Selecione uma pessoa</option>@for (person of availablePeople(); track person.id) { <option [value]="person.id">{{ person.name }} · {{ person.area }}</option> }</select></label><label>E-mail <input type="email" formControlName="email" /></label><label>Senha inicial <input type="password" formControlName="password" /></label><label>Perfil <select formControlName="roleKey">@for (role of roleOptions(); track role) { <option [value]="role">{{ roleLabel(role) }}</option> }</select></label><label>Status <select formControlName="status"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label>@if (validation()) { <p class="error">{{ validation() }}</p> }<div class="actions"><button type="button" class="secondary" (click)="cancel()">Cancelar</button><button type="submit" [disabled]="saving()">{{ saving() ? 'Salvando...' : 'Criar usuario' }}</button></div></form> }
@if (loading()) { <p>Carregando usuarios...</p> } @else if (!users().length) { <p>Nenhum usuario no seu escopo.</p> } @else { <div class="table"><table><thead><tr><th>Pessoa</th><th>E-mail</th><th>Perfil</th><th>Status</th><th></th></tr></thead><tbody>@for (user of users(); track user.id) { <tr><td><strong>{{ user.personName }}</strong><small>{{ user.personArea }} · {{ user.personRoleTitle || '-' }}</small></td><td>{{ user.email }}</td><td>{{ roleLabel(user.roleKey) }}</td><td>{{ user.status === 'active' ? 'Ativo' : 'Inativo' }}</td><td><button type="button" class="secondary" (click)="startEdit(user)">Editar</button></td></tr>
@if (selectedUser()?.id === user.id) { <tr class="inline-row"><td colspan="5"><form class="inline-edit" [formGroup]="form" (ngSubmit)="save()"><label>Pessoa <input [value]="user.personName" disabled /></label><label>E-mail <input type="email" formControlName="email" /></label><label>Perfil <select formControlName="roleKey">@for (role of roleOptions(); track role) { <option [value]="role">{{ roleLabel(role) }}</option> }</select></label><label>Status <select formControlName="status"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label><label>Nova senha <input type="password" formControlName="password" placeholder="Opcional" /></label>@if (validation()) { <p class="error">{{ validation() }}</p> }<div class="actions"><button type="button" class="secondary" (click)="cancel()">Cancelar</button><button type="submit" [disabled]="saving()">{{ saving() ? 'Salvando...' : 'Atualizar acesso' }}</button></div></form></td></tr> } }</tbody></table></div> }
<app-audit-trail [entries]="auditEntries()" title="Trilha de acesso" subtitle="Provisionamento e manutencao recentes" emptyMessage="Eventos de usuarios aparecerao aqui." /></section>`, styles: `
.users{max-width:1040px}header{display:flex;justify-content:space-between;gap:24px;align-items:start}header p{margin:0 0 8px;color:color-mix(in srgb, var(--abc-blue) 45%, var(--abc-surface));font-weight:700;text-transform:uppercase;font-size:13px}h1{margin:0;font-size:24px}header span,p,.journey span,.steps span{color:var(--abc-text-muted)}button{min-height:36px;padding:0 12px;border:0;border-radius:var(--abc-radius);background:var(--abc-blue);color:var(--abc-on-blue);font-weight:700;cursor:pointer}.secondary{background:var(--abc-surface);color:var(--abc-text);border:1px solid var(--abc-border)}.journey,.steps{display:grid;gap:14px;margin-top:24px}.journey{grid-template-columns:repeat(4,minmax(0,1fr))}.steps{grid-template-columns:repeat(2,minmax(0,1fr))}.journey div,.steps article,form,.table,.error{padding:20px;color:var(--abc-text);background:var(--abc-surface);border:1px solid var(--abc-border);border-radius:8px}.journey strong{display:block;margin-top:8px;font-size:24px}.steps article{display:grid;gap:6px}.steps .done{border-color:var(--abc-blue-dark);background:var(--abc-surface)}form,.table,.error{margin-top:24px}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}label{display:grid;gap:6px;color:var(--abc-text);font-weight:600}input,select{min-height:40px;padding:8px;color:var(--abc-text);background:var(--abc-surface);border:1px solid var(--abc-border);border-radius:var(--abc-radius);font:inherit}.actions,.error{grid-column:1/-1}.actions{display:flex;gap:8px;justify-content:end}.error{margin:0;color:color-mix(in srgb, var(--abc-danger) 28%, var(--abc-surface));background:color-mix(in srgb, var(--abc-danger) 30%, var(--abc-navy));border-color:color-mix(in srgb, var(--abc-danger) 55%, var(--abc-navy))}.table{overflow:auto;padding:0}table{width:100%;border-collapse:collapse}th,td{padding:14px 16px;text-align:left;border-bottom:1px solid var(--abc-border)}th{font-size:12px;color:var(--abc-text-muted);text-transform:uppercase}small{display:block;margin-top:4px;color:var(--abc-text-muted)}.inline-row td{padding:0 16px 16px;background:var(--abc-surface)}.inline-edit{margin-top:0;padding:16px;background:var(--abc-surface)}.inline-edit .error{margin:0}@media(max-width:760px){header{flex-direction:column;align-items:stretch}.journey,.steps,form{grid-template-columns:1fr}}
` })
export class UsersPageComponent implements OnInit {
 private readonly auth=inject(AuthService); private readonly usersService=inject(UsersService); private readonly peopleService=inject(PeopleService); private readonly auditService=inject(AuditService); private readonly fb=inject(FormBuilder);
 readonly users=signal<AdminUser[]>([]); readonly people=signal<Person[]>([]); readonly auditEntries=signal<AuditEntry[]>([]); readonly selectedUser=signal<AdminUser|null>(null); readonly editing=signal(false); readonly loading=signal(true); readonly saving=signal(false); readonly error=signal('');
 readonly form=this.fb.nonNullable.group({personId:['',Validators.required],email:['',[Validators.required,Validators.email]],password:[''],roleKey:['employee' as UserRoleKey,Validators.required],status:['active' as UserStatus,Validators.required]});
 readonly roleOptions=computed<readonly UserRoleKey[]>(()=>this.auth.user()?.roleKey==='manager'?['employee']:['admin','hr','manager','employee','compliance']);
 readonly availablePeople=computed(()=>{const linked=new Set(this.users().map(user=>user.personId));return this.people().filter(person=>!linked.has(person.id));});
 readonly activeUsers=computed(()=>this.users().filter(user=>user.status==='active').length);
 readonly inactiveUsers=computed(()=>this.users().filter(user=>user.status==='inactive').length);
 readonly pendingAccess=computed(()=>this.availablePeople().length);
 async ngOnInit():Promise<void>{await this.load();this.startCreate();}
 startCreate():void{const personId=this.availablePeople()[0]?.id||'';this.error.set('');this.selectedUser.set(null);this.form.reset({personId,email:this.suggestedEmail(personId),password:'',roleKey:this.suggestedRole(personId),status:'active'});this.editing.set(true);}
 startEdit(user:AdminUser):void{this.error.set('');this.selectedUser.set(user);this.form.reset({personId:user.personId,email:user.email,password:'',roleKey:this.roleOptions().includes(user.roleKey)?user.roleKey:'employee',status:user.status});this.editing.set(true);}
 cancel():void{this.editing.set(false);this.selectedUser.set(null);this.form.reset();}
 applyPersonSuggestion(personId:string):void{if(this.selectedUser())return;this.form.patchValue({email:this.suggestedEmail(personId),roleKey:this.suggestedRole(personId)});}
 validation():string{const v=this.form.getRawValue();if(!v.personId)return 'Selecione a pessoa vinculada ao usuario.';if(!v.email)return 'Informe o email de acesso.';if(!this.selectedUser()&&v.password.trim().length<6)return 'A senha inicial deve ter pelo menos 6 caracteres.';if(this.selectedUser()&&v.password&&v.password.trim().length<6)return 'A nova senha deve ter pelo menos 6 caracteres.';return '';}
 async save():Promise<void>{if(this.form.invalid||this.validation())return;this.saving.set(true);this.error.set('');try{const v=this.form.getRawValue(),user=this.selectedUser();if(user){const p:UpdateUserPayload={email:v.email,password:v.password,roleKey:v.roleKey,status:v.status};await firstValueFrom(this.usersService.update(user.id,p));}else{const p:CreateUserPayload={personId:v.personId,email:v.email,password:v.password,roleKey:v.roleKey,status:v.status};await firstValueFrom(this.usersService.create(p));}this.cancel();await this.load();}catch(e){this.error.set(e instanceof ApiError?e.message:'Nao foi possivel salvar o usuario.');}finally{this.saving.set(false);}}
 roleLabel(role:UserRoleKey):string{return ({admin:'Administrador',hr:'RH',manager:'Gestor',employee:'Colaborador',compliance:'Compliance'} as Record<UserRoleKey,string>)[role];}
 private suggestedEmail(personId:string):string{const person=this.people().find(item=>item.id===personId);const base=(person?.name||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'.').replace(/^\.+|\.+$/g,'').replace(/\.{2,}/g,'.');return base?`${base}@empresa.local`:'';}
 private suggestedRole(personId:string):UserRoleKey{const person=this.people().find(item=>item.id===personId);const next=this.auth.user()?.roleKey==='manager'?'employee':person&&(person.areaManagerPersonId===person.id||this.people().some(item=>item.managerPersonId===person.id))?'manager':'employee';return this.roleOptions().includes(next)?next:this.roleOptions()[0];}
 private async load():Promise<void>{this.loading.set(true);this.error.set('');try{const data=await firstValueFrom(forkJoin({users:this.usersService.list(),people:this.peopleService.list(),audit:this.auditService.list('user')}));this.users.set(data.users);this.people.set(data.people);this.auditEntries.set(data.audit);}catch(e){this.error.set(e instanceof ApiError?e.message:'Nao foi possivel carregar os usuarios.');}finally{this.loading.set(false);}}
}
