import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { firstValueFrom, forkJoin } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { ApiError } from '../../core/http/api-error';
import { Person, PeopleService } from '../people/people.service';
import { AuditService, AuditEntry } from '../audit/audit.service';
import { AuditTrailComponent } from '../audit/audit-trail.component';
import { AdminUser, CreateUserPayload, UpdateUserPayload, UserRoleKey, UserStatus, UsersService } from './users.service';

@Component({ selector: 'app-users-page', imports: [ReactiveFormsModule, AuditTrailComponent], template: `
<section class="users" aria-labelledby="users-title"><header><div><p>Cadastro</p><h1 id="users-title">Usuarios</h1><span>Gerencie acessos, perfis e status.</span></div><button type="button" (click)="startCreate()">Novo usuario</button></header>
@if (error()) { <p class="error" role="alert">{{ error() }}</p> }
@if (editing()) { <form [formGroup]="form" (ngSubmit)="save()"><label>Pessoa @if (!selectedUser()) { <select formControlName="personId"><option value="" disabled>Selecione uma pessoa</option>@for (person of availablePeople(); track person.id) { <option [value]="person.id">{{ person.name }} · {{ person.area }}</option> }</select> } @else { <input [value]="selectedUser()!.personName" disabled /> }</label><label>E-mail <input type="email" formControlName="email" /></label><label>{{ selectedUser() ? 'Nova senha (opcional)' : 'Senha inicial' }} <input type="password" formControlName="password" /></label><label>Perfil <select formControlName="roleKey">@for (role of roleOptions(); track role) { <option [value]="role">{{ roleLabel(role) }}</option> }</select></label><label>Status <select formControlName="status"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label>@if (validation()) { <p class="error">{{ validation() }}</p> }<div class="actions"><button type="button" class="secondary" (click)="cancel()">Cancelar</button><button type="submit" [disabled]="saving()">{{ saving() ? 'Salvando...' : selectedUser() ? 'Atualizar acesso' : 'Criar usuario' }}</button></div></form> }
@if (loading()) { <p>Carregando usuarios...</p> } @else if (!users().length) { <p>Nenhum usuario no seu escopo.</p> } @else { <div class="table"><table><thead><tr><th>Pessoa</th><th>E-mail</th><th>Perfil</th><th>Status</th><th></th></tr></thead><tbody>@for (user of users(); track user.id) { <tr><td><strong>{{ user.personName }}</strong><small>{{ user.personArea }} · {{ user.personRoleTitle || '-' }}</small></td><td>{{ user.email }}</td><td>{{ roleLabel(user.roleKey) }}</td><td>{{ user.status === 'active' ? 'Ativo' : 'Inativo' }}</td><td><button type="button" class="secondary" (click)="startEdit(user)">Editar</button></td></tr> }</tbody></table></div> }
<app-audit-trail [entries]="auditEntries()" title="Trilha de acesso" subtitle="Provisionamento e manutencao recentes" emptyMessage="Eventos de usuarios aparecerao aqui." /></section>`, styles: `
.users{max-width:1040px}header{display:flex;justify-content:space-between;gap:24px;align-items:start}header p{margin:0 0 8px;color:#175cd3;font-weight:700;text-transform:uppercase;font-size:13px}h1{margin:0;font-size:24px}header span,p{color:#475467}button{min-height:36px;padding:0 12px;border:0;border-radius:6px;background:#175cd3;color:#fff;font-weight:600;cursor:pointer}.secondary{background:#fff;color:#344054;border:1px solid #98a2b3}form,.table,.error{margin-top:24px;padding:20px;background:#fff;border:1px solid #d0d5dd;border-radius:8px}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}label{display:grid;gap:6px;color:#344054;font-weight:600}input,select{min-height:40px;padding:8px;border:1px solid #98a2b3;border-radius:6px;font:inherit}.actions,.error{grid-column:1/-1}.actions{display:flex;gap:8px;justify-content:end}.error{margin:0;color:#b42318;background:#fef3f2;border-color:#fecdca}.table{overflow:auto;padding:0}table{width:100%;border-collapse:collapse}th,td{padding:14px 16px;text-align:left;border-bottom:1px solid #eaecf0}th{font-size:12px;color:#475467;text-transform:uppercase}small{display:block;margin-top:4px;color:#667085}@media(max-width:640px){header{flex-direction:column;align-items:stretch}form{grid-template-columns:1fr}}
` })
export class UsersPageComponent implements OnInit {
 private readonly auth=inject(AuthService); private readonly usersService=inject(UsersService); private readonly peopleService=inject(PeopleService); private readonly auditService=inject(AuditService); private readonly fb=inject(FormBuilder);
 readonly users=signal<AdminUser[]>([]); readonly people=signal<Person[]>([]); readonly auditEntries=signal<AuditEntry[]>([]); readonly selectedUser=signal<AdminUser|null>(null); readonly editing=signal(false); readonly loading=signal(true); readonly saving=signal(false); readonly error=signal('');
 readonly form=this.fb.nonNullable.group({personId:['',Validators.required],email:['',[Validators.required,Validators.email]],password:[''],roleKey:['employee' as UserRoleKey,Validators.required],status:['active' as UserStatus,Validators.required]});
 readonly roleOptions=computed<readonly UserRoleKey[]>(()=>this.auth.user()?.roleKey==='manager'?['employee']:['admin','hr','manager','employee','compliance']);
 readonly availablePeople=computed(()=>{const linked=new Set(this.users().map(user=>user.personId));return this.people().filter(person=>!linked.has(person.id));});
 ngOnInit():void{void this.load();}
 startCreate():void{this.error.set('');this.selectedUser.set(null);this.form.reset({personId:this.availablePeople()[0]?.id||'',email:'',password:'',roleKey:this.roleOptions()[0],status:'active'});this.editing.set(true);}
 startEdit(user:AdminUser):void{this.error.set('');this.selectedUser.set(user);this.form.reset({personId:user.personId,email:user.email,password:'',roleKey:this.roleOptions().includes(user.roleKey)?user.roleKey:'employee',status:user.status});this.editing.set(true);}
 cancel():void{this.editing.set(false);this.selectedUser.set(null);this.form.reset();}
 validation():string{const v=this.form.getRawValue();if(!v.personId)return 'Selecione a pessoa vinculada ao usuario.';if(!v.email)return 'Informe o email de acesso.';if(!this.selectedUser()&&v.password.trim().length<6)return 'A senha inicial deve ter pelo menos 6 caracteres.';if(this.selectedUser()&&v.password&&v.password.trim().length<6)return 'A nova senha deve ter pelo menos 6 caracteres.';return '';}
 async save():Promise<void>{if(this.form.invalid||this.validation())return;this.saving.set(true);this.error.set('');try{const v=this.form.getRawValue(),user=this.selectedUser();if(user){const p:UpdateUserPayload={email:v.email,password:v.password,roleKey:v.roleKey,status:v.status};await firstValueFrom(this.usersService.update(user.id,p));}else{const p:CreateUserPayload={personId:v.personId,email:v.email,password:v.password,roleKey:v.roleKey,status:v.status};await firstValueFrom(this.usersService.create(p));}this.cancel();await this.load();}catch(e){this.error.set(e instanceof ApiError?e.message:'Nao foi possivel salvar o usuario.');}finally{this.saving.set(false);}}
 roleLabel(role:UserRoleKey):string{return ({admin:'Administrador',hr:'RH',manager:'Gestor',employee:'Colaborador',compliance:'Compliance'} as Record<UserRoleKey,string>)[role];}
 private async load():Promise<void>{this.loading.set(true);this.error.set('');try{const data=await firstValueFrom(forkJoin({users:this.usersService.list(),people:this.peopleService.list(),audit:this.auditService.list('user')}));this.users.set(data.users);this.people.set(data.people);this.auditEntries.set(data.audit);}catch(e){this.error.set(e instanceof ApiError?e.message:'Nao foi possivel carregar os usuarios.');}finally{this.loading.set(false);}}
}
